### ISSUE TITLE
constant motion design

### ISSUE THREAD

**Issue by russellsamora** [the-pudding/three-seconds#11]

**Comment by jadiehm** [comment]
For the opener, try this:

- Slide in green 3-point outline (this should slide in under the top text "THE NBA HAS A" and the bottom text "PROBLEM" to reveal it)
- Stagger slide in purple key, orange paint, "DEFENSIVE", "THREE", SECONDS"
- Slide in Lebron
- At the same time the Lebron motion starts, quickly fade in the byline copy one line at a time
- Once all motion has paused for a beat, quickly fade in P logo in corner
- Pause again for a beat
- Slide out as it is currently
