### ISSUE TITLE
report: celebration gif

### ISSUE THREAD

**Issue by russellsamora** [the-pudding/three-seconds#3]
* https://giphy.com/gifs/nba-spike-lee-26xBQF0U6opqsDb1e
* https://giphy.com/gifs/laclippers-basketball-clippers-la-4HgqVpNGRvf53hTxff
* https://giphy.com/gifs/harlemglobetrotters-clapping-harlem-globetrotters-6TQUHMnaGC448
* https://giphy.com/gifs/nba-rookies-nba-2018-19-7XuB9dwcPNjPq6t2X9

**Comment by russellgoldenberg** [comment]
https://giphy.com/gifs/harlemglobetrotters-clapping-harlem-globetrotters-6TQUHMnaGC448

**Comment by russellsamora** [comment]
Could either jump cut, or put a sticker on it
